name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: dependencies 설치
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: 전체 소스 코드와 빌드 파일 복사
        run: |
          mkdir full-project
          cp -r dist full-project/dist
          cp -r * full-project/
          rm -rf full-project/node_modules
          rm -rf full-project/.git

      - name: 복사한 아티팩트 업로드
        uses: actions/upload-artifact@v4
        with:
          name: full-project-with-build
          path: full-project/
