name: release

on:
  push:
    branches:
      - master
      - set-cd-release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Github의 최신 tag 받아오기
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: release 업데이트
        id: release_update
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: 결과 출력
        run: |
          echo "tag: ${{ steps.release_update.outputs.tag }}"
          echo "release_id: ${{ steps.release_update.outputs.name }}"
          echo "release_url: ${{ steps.release_update.outputs.url }}"
