name: release

on:
  push:
    branches:
      - master
      - set-cd-release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Github의 최신 tag 받아오기
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 브랜치 이름 제거
        id: sanitize_tag
        run: echo "::set-output name=sanitized_tag::$(echo '${{ steps.tag_version.outputs.new_tag }}' | sed -E 's/-.*//')"

      - name: release 업데이트
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.sanitize_tag.outputs.sanitized_tag }}
          name: Release ${{ steps.sanitize_tag.outputs.sanitized_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
